//
// Created by samuel on 1-11-22.
//

#ifndef FLATCAM_PCB_MAKER_APP_VERSION_H
#define FLATCAM_PCB_MAKER_APP_VERSION_H

const char* APP_VERSION = "0.3.0-SNAPSHOT";

#endif //FLATCAM_PCB_MAKER_APP_VERSION_H
