//
// Created by samuel on 22-9-22.
//

#include "checklist.h"

const char *checklist_checks[] = {
        "-- Computer --",
        "Export EAGLE files",
        "Run FlatCAM scripts",
        "Modify GCode files",
        "-- Preparation --",
        "Mount Dremel tool on printer with knob facing X axis direction",
        "Saw the board",
        "Set clamp",
        "Clean board",
        "Cover the board with ink from a permanent marker",
        "Secure board in clamp",
        "Align print head Z-axis with board surface",
        "Adjust Z offset screw for Z-axis homing allignment with board surface",
        "Backup manual mesh by taking a photo of it",
        "Perform a manual mesh accros board",
        "-- Print traces --",
        "Home all axis",
        "Reset Z-offset to 0.0",
        "Turn on Dremel to 14000 RPM",
        "Start 0_draw_traces print",
        "-- Etch --",
        "Turn printer off",
        "Remove board from clamp",
        "Gentle blow off any copper dust",
        "Mark GND pads with a permanent marker",
        "Put board in etching solution",
        "Remove board from etching solution",
        "Clean the board",
        "Remove the ink from the board",
        "-- Silkscreen --",
        "Put board back in clamp",
        "Measure distance from clamp left side to left side of profile",
        "Make sure this distance is available on the right sid of the board",
        "Flip over board and make sure the correct distance is maintained between the clamp and the profile",
        "Turn on Dremel to 14000 RPM",
        "Start 1_draw_silkscreen print",
        "-- Drilling --",
        "Remove board from clamp",
        "Put tape on top of the board (copper side) (not the sides!)",
        "Change Dremel bit",
        "Secure board in clamp (copper side up)",
        "Align print head Z-axis with board surface",
        "Turn on the printer",
        "Home X and Y axis",
        "Start 1_check_holes_cnc print",
        "Adjust X axis screw for the holes",
        "Restart 2_check_holes print and repeat as needed",
        "Home X and Y axis",
        "Start 3_drill_holes print",
        "During the start of this print, set Z-offset to -3.0",
        "-- Finish --",
        "Reset Z-offset to 0.0",
        "Turn off printer and Dremel tool",
        "Remove board from clamp",
        "Remove tape from board",
};

const int checklist_length = (sizeof (checklist_checks) / sizeof (const char *));